import React from 'react';
import { motion } from 'framer-motion';
import { Shield, Eye, Database, Lock, Bell, Mail } from 'lucide-react';

const sections = [
  {
    icon: Eye,
    title: 'Information We Do Not Collect',
    content:
      'Video Downloader App does not collect, store, or transmit any personal information. We have no analytics, no tracking pixels, no crash reporters, and no third-party SDKs that phone home. Your usage is entirely private.',
  },
  {
    icon: Database,
    title: 'Local Data Only',
    content:
      'All data generated by the app — download history, settings, and preferences — is stored exclusively on your device. Nothing is synced to any server we operate. Uninstalling the app removes all associated data.',
  },
  {
    icon: Lock,
    title: 'Network Requests',
    content:
      'The app makes network requests solely to the URLs you provide (the video source) and to download the resulting media. No requests are made to our servers, advertising networks, or any analytics endpoint.',
  },
  {
    icon: Shield,
    title: 'Third-Party Services',
    content:
      'This website is hosted on Vercel. Their privacy policy applies to web traffic logs. The app itself does not use any third-party analytics or advertising services.',
  },
  {
    icon: Bell,
    title: 'Changes to This Policy',
    content:
      'If this policy changes materially, an updated version will be published on this page with a revised effective date. Continued use of the app or website constitutes acceptance of the updated policy.',
  },
  {
    icon: Mail,
    title: 'Contact',
    content:
      'If you have any questions about this privacy policy, please open an issue on our GitHub repository or reach out via the Contact page.',
  },
];

const Privacy = () => (
  <div className="min-h-screen bg-white dark:bg-gray-900">
    <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-16 max-w-3xl">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="mb-12"
      >
        <div className="inline-flex items-center space-x-2 px-3 py-1 bg-teal-100 dark:bg-teal-900/30 text-teal-700 dark:text-teal-300 rounded-full text-sm font-medium mb-4">
          <Shield className="w-4 h-4" />
          <span>Privacy First</span>
        </div>
        <h1 className="text-4xl md:text-5xl font-bold mb-4 text-gray-900 dark:text-white">
          Privacy Policy
        </h1>
        <p className="text-lg text-gray-600 dark:text-gray-400">
          Effective date: <strong>March 8, 2026</strong>
        </p>
        <p className="mt-4 text-gray-600 dark:text-gray-400">
          Video Downloader App is built on a simple principle: your data is yours. This policy explains what we do (and don't do) with information related to the app and this website.
        </p>
      </motion.div>

      <div className="space-y-8">
        {sections.map((section, i) => {
          const Icon = section.icon;
          return (
            <motion.div
              key={section.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.07, duration: 0.5 }}
              className="flex space-x-4"
            >
              <div className="flex-shrink-0 w-10 h-10 bg-teal-100 dark:bg-teal-900/30 rounded-lg flex items-center justify-center mt-1">
                <Icon className="w-5 h-5 text-teal-600 dark:text-teal-400" />
              </div>
              <div>
                <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
                  {section.title}
                </h2>
                <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                  {section.content}
                </p>
              </div>
            </motion.div>
          );
        })}
      </div>
    </div>
  </div>
);

export default Privacy;
